### ISSUE TITLE
What is stack used for in "Hello World" example?

### ISSUE THREAD

**Issue by mydoghasworms** [Schweigi/assembler-simulator#19]
Hello, thanks for this very entertaining piece of work! I am new to assembly, so I was wondering why the A and B registers are pushed on to the stack before the print and then popped off at the end.

**Comment by mrclay** [comment]
From what I can tell, print uses A and B as local storage, and just to be nice it restores them to their previous values after it ends. StackOverflow might be a better place for this discussion.

**Comment by mydoghasworms** [comment]
Thanks! Sorry, you are right, this is not really an issue :-/
